on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4  
        with:
          python-version: '3.11.5'
          cache: 'pip' 

      - run: pip cache dir  # optionnel : montre le dossier utilisé pour le cache

      - name: Vérification du fichier requirements.txt
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo "requirements.txt n'existe pas dans le répertoire courant."
            exit 1
          fi

      - name: Mise à jour de pip
        run: python -m pip install --upgrade pip

      - name: Installation des dépendances
        run: python -m pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
