on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'
          cache: 'pip'

      # Ajoutez une commande pour vérifier la présence de requirements.txt
      - run: ls -la
      - run: |
          if [ ! -f "requirements.txt" ]; then
            echo "requirements.txt n'existe pas dans le répertoire courant."
            exit 1
          fi
      
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
